### ISSUE TITLE
Missing indention

### ISSUE THREAD

**Issue by philres** [jeffdaily/parasail-python#19]
Hi Jeff,

it's me again. I'm currently testing 1.1.10 and came across a missing indention in `bindigns_v1.py`:

https://github.com/jeffdaily/parasail-python/blob/9c413a1a9bdf8cef91ffe0f8f41dcefd1c8dea74/parasail/bindings_v1.py#L284

**Comment by jeffdaily** [comment]
Thanks for that.  Easy fix.
