### ISSUE TITLE
new symbol not found problem on OS X on parasail import

### ISSUE THREAD

**Issue by tlambert03** [jeffdaily/parasail-python#28]
during an environment rebuild today on a mac that was previously running parasail just fine, parasail is having a new problem due to the traceback property added in fc3add4.

`python setup.py install` builds fine, but then when trying to import, there is an issue with the dylib.

```
>>> import parasail
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/Downloads/parasail-python-master/parasail/__init__.py", line 53, in <module>
    from parasail.bindings_v2 import *
  File "~/Downloads/parasail-python-master/parasail/bindings_v2.py", line 689, in <module>
    _lib.parasail_result_get_traceback.argtypes = [c_result_p, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_int, c_matrix_p, ctypes.c_char, ctypes.c_char, ctypes.c_char]
  File "~/anaconda3/envs/test36/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "~/anaconda3/envs/test36/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7ff09ee02430, parasail_result_get_traceback): symbol not found
```

if I rollback to b0a6d0b and rebuild, then the import works fine.

thanks!

**Comment by jeffdaily** [comment]
Sorry about that. I know what happened. I was developing new features in the C library but haven’t pushed a new release. However I added support for those features in the python wrappers. I’ll try to get a new release of the C library ASAP.  Thanks.

**Comment by tlambert03** [comment]
Thanks, no hurry! I'm good working with b0a6d0b for now...

FYI: I really like parasail and I'm starting to integrate deeper into the backend at https://github.com/tlambert03/FPbase (www.fpbase.org).  the server environment is linux, so it works pretty seamlessly in deployment, it's just my os x dev environment that runs into issues from time to time.

**Comment by tlambert03** [comment]
works great, thanks!
