### ISSUE TITLE
Broken Python3 string encoding conversion

### ISSUE THREAD

**Issue by hernot** [jeffdaily/parasail-python#30]
In pyhton3 all strings are utf-8 and unless using only the first 128 characters (ASCII 0-127) they will be represented as multibyte characters. In Python3 the bytes string corresponds to the python2 string. In order to get the proper bytes representation of a python string the conversion functions have to be modified as follows

def b(x):
   if not isstr(x):
       if isbytes(x):
          return x
       x = str(x)
   return x.encode('utf-8')

def s(x):
    if not isbytes(x):
        return x
    return x.decode('utf-8')

further sets, lists and others sequences passed should be first joined by the caller of parasail methods using for example
  ''.join((str(_item) for item in <secuence>)) 

as 
str({<key1>:<val1>,<key2>:<val2>,...,<keyn>:<valn>}) -> '{<key1>:<val1>, <key2>:<val2>, .... <keyn>:<valn>'

str([<item1>, <item2>, ... , <itemn>]) -> '[<item1>, <item2>, ... <itemn>]'

and so forth

**Comment by jeffdaily** [comment]
Please format the code block in your issue.

I am aware that python3 uses unicode strings.  The interface to the underlying parasail C library assumes ASCII characters.  In parasail-python, I make the attempt to encode and decode the python3 strings to bytes as needed using the following code:

```python
import codecs
def isstr(s):
    return isinstance(s, str)
def isbytes(s):
    return isinstance(s, (bytes, bytearray))
def b(x):
    if isstr(x):
        return codecs.latin_1_encode(str(x))[0]
    else:
        return x
def s(x):
    if isbytes(x):
        return codecs.latin_1_decode(x)[0]
    else:
        return x
```

Thus far this has been sufficient.  Do you have a use case for non-ASCII sequence alignments?

**Comment by hernot** [comment]
This is related to the issue jeffdaily/parasail#65 about the alphabets with more than 256 characters. If the python string is directly decoded to utf-8 binary representation than it is at least possible to mapp the whole string to 256 characters. further the str function converts lists, sets and others to their literal string representation which is [<item>, ...] or {<item>,... } which explicitly includes the [, ], {, }, (, ) characters. It would be better to raise an exception if the passed value is not a valid python string and have the user convert it first to an appropriate string or use 

    ''.join((str(_c) for _c in x))

as this will yield a string without the intermittent ', ' sequence and the [, ], {, }, (, ) to do the conversion of sets, lists, tuples and others storing the symbols of the alphabet should be supported at all.

**Comment by jeffdaily** [comment]
I can understand not converting lists, sets, etc.  I could certainly raise an exception if the given sequence inputs are invalid i.e., not strings or bytes.

Concerning alphabets with more than 256 characters, is the issue because I used `codecs.latin_1_decode` instead of `codecs.decode('utf-8')`?

**Comment by hernot** [comment]
Partially as it at least would allow to pass multibyte utf-characters as individual not related symbols to parasail getting at least an impression on how dissimilar the strings are. With latin1 strings containing symbols not encodable in latin1 can not compared at all. Proper matching of these multibyte symbols would need support from parasail library directly as indicated by referenced issue. Alternatively allow users to configure through a setup method which encoding to use 

_parasail_encoding = 'latin1'

def parasail_set_encoding(encoding):
   try:
      (''.encode(encoding)).decode(encoding)
   except:
      raise Exception("Encoding '{}' not supported".format(encoding)
   _parasail_encoding = encoding

def b()
    if isstr(x):
        return x.encode(_parasail_encoding)
    else:
        return x
def s(x):
    if isbytes(x):
        return x.decode(_parasail_encoding)
    else:
        return x

Than the current behavior is preserved and if different encoding eg utf-8 should be used than  this can be changed by calling 

parasail_set_encoding('utf-8')
