### ISSUE TITLE
libparasail.so missing in 1.1.15

### ISSUE THREAD

**Issue by kulesha** [jeffdaily/parasail-python#33]
ubuntu:$ find / -name '_parasail_' 2>&1 | grep para
/usr/local/lib/python2.7/dist-packages/parasail
/usr/local/lib/python2.7/dist-packages/parasail/parasail.dll
/usr/local/lib/python2.7/dist-packages/parasail-1.1.15.dist-info
/usr/local/lib/python3.5/dist-packages/parasail
/usr/local/lib/python3.5/dist-packages/parasail/parasail.dll
/usr/local/lib/python3.5/dist-packages/parasail-1.1.15.dist-info
ubuntu:$

installed version 1.1.14 and .so file is back

ubuntu:$ find / -name '_parasail_' 2>&1 | grep para
/usr/local/lib/python2.7/dist-packages/parasail
/usr/local/lib/python2.7/dist-packages/parasail/libparasail.so
/usr/local/lib/python2.7/dist-packages/parasail/parasail.dll
/usr/local/lib/python2.7/dist-packages/parasail-1.1.14-py2.7.egg-info
/usr/local/lib/python2.7/dist-packages/parasail-1.1.15.dist-info
/usr/local/lib/python3.5/dist-packages/parasail
/usr/local/lib/python3.5/dist-packages/parasail/parasail.dll
/usr/local/lib/python3.5/dist-packages/parasail-1.1.15.dist-info
ubuntu:$

**Comment by jeffdaily** [comment]
What exactly is your install command?  pip?  setup.py?

**Comment by jeffdaily** [comment]
Or I could just try to reproduce, because your error messages were absolutely correct had I looked more closely.

Fascinating.  pip installing version 1.1.14 will run `python setup.py bdist_wheel` (which will download the parasail C library and build it), but pip installing version 1.1.15 will download a wheel with `parasail.dll`.  Looking into this now.

**Comment by kulesha** [comment]
pip install parasail

thanks for looking into it so quickly !

**Comment by jeffdaily** [comment]
One major difference is the set of packages hosted by pypi.  For release 1.1.15, there appears `parasail-1.1.15-py2.py3-none-any.whl (1.7 MB)  Copy SHA256 hash SHA256` and this "any" wheel doesn't appear for any other releases.  I manually removed it from pypi but it didn't work around the issue yet.  I'm looking at how my distributions are packaged now.

**Comment by jeffdaily** [comment]
I verified that it is my appveyor packaging causing the rogue whl file.

**Comment by jeffdaily** [comment]
I think we're all good now.  I just tagged v1.1.16 to kick off a new pypi version.  Thank you for reporting and thanks for being a user.

**Comment by kulesha** [comment]
i can confirm that all is good again in 1.1.16
thanks for your work and incredibly quick fix !

**Comment by daniil-lyakhov** [comment]
Same behavior at parasail-1.2-py3.7.egg (1.2)

**Comment by jeffdaily** [comment]
@daniil-lyakhov please open a new ticket with more details.
