### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by ascendo** [jeffdaily/parasail-python#35]
Hello,
I use GCC 5.4.0 and configure cannot read the gcc.
Can you please check this below?

Thanks.

## --------- ##

hostname = login-0
uname -m = x86_64
uname -r = 3.10.0-693.21.1.el7.x86_64
uname -s = Linux
uname -v = #1 SMP Wed Mar 7 19:03:37 UTC 2018

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /cm/shared/apps/gcc/5.4.0/bin
PATH: /data/gpfs/home/wyim/scratch/bin/miniconda2/envs/isonclust/bin
PATH: /apps/singularity/2.6.0/bin
PATH: /cm/shared/apps/slurm/17.02.2/sbin
PATH: /cm/shared/apps/slurm/17.02.2/bin
PATH: /usr/local/bin
PATH: /usr/bin
PATH: /usr/local/sbin
PATH: /usr/sbin
PATH: /sbin
PATH: /usr/sbin
PATH: /cm/local/apps/environment-modules/3.2.10/bin
PATH: /opt/dell/srvadmin/bin
PATH: .

## ----------- ##

configure:3073: checking whether make supports nested variables
configure:3090: result: yes
configure:3163: checking for a BSD-compatible install
configure:3231: result: /usr/bin/install -c
configure:3242: checking whether build environment is sane
configure:3297: result: yes
configure:3448: checking for a thread-safe mkdir -p
configure:3487: result: /usr/bin/mkdir -p
configure:3494: checking for gawk
configure:3510: found /usr/bin/gawk
configure:3521: result: gawk
configure:3532: checking whether make sets $(MAKE)
configure:3554: result: yes
configure:3648: checking whether to enable maintainer-specific portions of Makefiles
configure:3657: result: no
configure:3678: checking build system type
configure:3692: result: x86_64-unknown-linux-gnu
configure:3712: checking host system type
configure:3725: result: x86_64-unknown-linux-gnu
configure:3833:
configure:3835: C compiler
configure:3837:
configure:3852: checking for style of include used by make
configure:3880: result: GNU
configure:3951: checking for gcc
configure:3967: found /cm/shared/apps/gcc/5.4.0/bin/gcc
configure:3978: result: gcc
configure:4207: checking for C compiler version
configure:4216: gcc --version >&5
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:4227: $? = 0
configure:4216: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/cm/shared/apps/gcc/5.4.0/libexec/gcc/x86_64-unknown-linux-gnu/5.4.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/cm/shared/apps/gcc/5.4.0/ --enable-languages=c,c++,fortran
Thread model: posix
gcc version 5.4.0 (GCC)
configure:4227: $? = 0
configure:4216: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:4227: $? = 1
configure:4216: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:4227: $? = 1
configure:4247: checking whether the C compiler works
configure:4269: gcc -I/data/gpfs/assoc/pgl/library/include -I/data/gpfs/home/wyim/scratch/bin/sqlite/include -I/data/gpfs/home/wyim/scratch/bin/R/lib64/R/include -I/data/gpfs/assoc/pgl/bin/R/Rcpp/include  -L/data/gpfs/assoc/pgl/library/lib -L/data/gpfs/assoc/pgl/library/lib64 -L/data/gpfs/home/wyim/scratch/bin/sqlite/lib -L conftest.c  >&5
gcc: fatal error: no input files
compilation terminated.
configure:4273: $? = 1
configure:4311: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "Pairwise Sequence Alignment Library"
| #define PACKAGE_TARNAME "parasail"
| #define PACKAGE_VERSION "2.4.0"
| #define PACKAGE_STRING "Pairwise Sequence Alignment Library 2.4.0"
| #define PACKAGE_BUGREPORT "jeff.daily@pnnl.gov"
| #define PACKAGE_URL ""
| #define PACKAGE "parasail"
| #define VERSION "2.4.0"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4316: error: in `/data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master':
configure:4318: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-I/data/gpfs/assoc/pgl/library/include -I/data/gpfs/home/wyim/scratch/bin/sqlite/include -I/data/gpfs/home/wyim/scratch/bin/R/lib64/R/include -I/data/gpfs/assoc/pgl/bin/R/Rcpp/include'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-L/data/gpfs/assoc/pgl/library/lib -L/data/gpfs/assoc/pgl/library/lib64 -L/data/gpfs/home/wyim/scratch/bin/sqlite/lib -L'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_PKG_CONFIG_LIBDIR_set=
ac_cv_env_PKG_CONFIG_LIBDIR_value=
ac_cv_env_PKG_CONFIG_PATH_set=
ac_cv_env_PKG_CONFIG_PATH_value=
ac_cv_env_PKG_CONFIG_set=
ac_cv_env_PKG_CONFIG_value=
ac_cv_env_Z_CFLAGS_set=
ac_cv_env_Z_CFLAGS_value=
ac_cv_env_Z_LIBS_set=
ac_cv_env_Z_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master/build-aux/missing aclocal-1.13'
ALTIVEC_CFLAGS=''
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR=''
AS=''
AUTOCONF='${SHELL} /data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master/build-aux/missing autoconf'
AUTOHEADER='${SHELL} /data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master/build-aux/missing autoheader'
AUTOMAKE='${SHELL} /data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master/build-aux/missing automake-1.13'
AVX2_CFLAGS=''
AVX512BW_CFLAGS=''
AVX512F_CFLAGS=''
AVX512VBMI_CFLAGS=''
AWK='gawk'
CC='gcc'
CCDEPMODE=''
CFLAGS='-I/data/gpfs/assoc/pgl/library/include -I/data/gpfs/home/wyim/scratch/bin/sqlite/include -I/data/gpfs/home/wyim/scratch/bin/R/lib64/R/include -I/data/gpfs/assoc/pgl/bin/R/Rcpp/include'
CLOCK_LIBS=''
CPP=''
CPPFLAGS=''
CROSS_COMPILING_FALSE=''
CROSS_COMPILING_TRUE=''
CXX=''
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
FGREP=''
GREP=''
HAVE_ALTIVEC_FALSE=''
HAVE_ALTIVEC_TRUE=''
HAVE_AVX2_FALSE=''
HAVE_AVX2_TRUE=''
HAVE_AVX512BW_FALSE=''
HAVE_AVX512BW_TRUE=''
HAVE_AVX512F_FALSE=''
HAVE_AVX512F_TRUE=''
HAVE_AVX512VBMI_FALSE=''
HAVE_AVX512VBMI_TRUE=''
HAVE_NEON_FALSE=''
HAVE_NEON_TRUE=''
HAVE_OPENMP_FALSE=''
HAVE_OPENMP_TRUE=''
HAVE_SSE2_FALSE=''
HAVE_SSE2_TRUE=''
HAVE_SSE41_FALSE=''
HAVE_SSE41_TRUE=''
HAVE_SSE_FALSE=''
HAVE_SSE_TRUE=''
HAVE_XGETBV_FALSE=''
HAVE_XGETBV_TRUE=''
HAVE_ZLIB_FALSE=''
HAVE_ZLIB_TRUE=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
IS_ARM_ISA_FALSE=''
IS_ARM_ISA_TRUE='#'
IS_POWER_ISA_FALSE=''
IS_POWER_ISA_TRUE='#'
LD=''
LDFLAGS='-L/data/gpfs/assoc/pgl/library/lib -L/data/gpfs/assoc/pgl/library/lib64 -L/data/gpfs/home/wyim/scratch/bin/sqlite/lib -L'
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LTVER='7:0:4'
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} /data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master/build-aux/missing makeinfo'
MANIFEST_TOOL=''
MATH_LIBS=''
MKDIR_P='/usr/bin/mkdir -p'
NEON_CFLAGS=''
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
ON_CYGWIN_FALSE=''
ON_CYGWIN_TRUE=''
ON_MINGW_FALSE=''
ON_MINGW_TRUE=''
ON_MSYS_FALSE=''
ON_MSYS_TRUE=''
OPENMP_CFLAGS=''
OPENMP_CXXFLAGS=''
OTOOL64=''
OTOOL=''
PACKAGE='parasail'
PACKAGE_BUGREPORT='jeff.daily@pnnl.gov'
PACKAGE_NAME='Pairwise Sequence Alignment Library'
PACKAGE_STRING='Pairwise Sequence Alignment Library 2.4.0'
PACKAGE_TARNAME='parasail'
PACKAGE_URL=''
PACKAGE_VERSION='2.4.0'
PATH_SEPARATOR=':'
PKG_CONFIG=''
PKG_CONFIG_LIBDIR=''
PKG_CONFIG_PATH=''
RANLIB=''
SED=''
SET_MAKE=''
SHELL='/bin/sh'
SSE2_CFLAGS=''
SSE41_CFLAGS=''
STRIP=''
VERSION='2.4.0'
VISIBILITY_CFLAGS=''
Z_CFLAGS=''
Z_LIBS=''
ac_ct_AR=''
ac_ct_CC='gcc'
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /data/gpfs/assoc/pgl/data/orchid/Won/ccs_bam/parasail-python/parasail-master/build-aux/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
pkgconfig_libdir=''
pkgconfig_libfile=''
pkgconfigdir=''
prefix='NONE'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "Pairwise Sequence Alignment Library"
#define PACKAGE_TARNAME "parasail"
#define PACKAGE_VERSION "2.4.0"
#define PACKAGE_STRING "Pairwise Sequence Alignment Library 2.4.0"
#define PACKAGE_BUGREPORT "jeff.daily@pnnl.gov"
#define PACKAGE_URL ""
#define PACKAGE "parasail"
#define VERSION "2.4.0"

configure: exit 77

**Comment by jeffdaily** [comment]
Error is here:
```
configure:4269: gcc -I/data/gpfs/assoc/pgl/library/include -I/data/gpfs/home/wyim/scratch/bin/sqlite/include -I/data/gpfs/home/wyim/scratch/bin/R/lib64/R/include -I/data/gpfs/assoc/pgl/bin/R/Rcpp/include -L/data/gpfs/assoc/pgl/library/lib -L/data/gpfs/assoc/pgl/library/lib64 -L/data/gpfs/home/wyim/scratch/bin/sqlite/lib -L conftest.c >&5
```
I'm not sure what your LIBS and LD_FLAGS env vars are set to, but you've got an empty `-L` at the end that is consuming the `conftest.c` command-line parameter.  Make sure your env vars are correct.

**Comment by ascendo** [comment]
Thanks. I fixed LD_FLAGS and problem was solved.
