### ISSUE TITLE
Semi-global alignment results printing

### ISSUE THREAD

**Issue by suzannejin** [jeffdaily/parasail-python#37]
I want to do pairwise semi-global alignments of a set of proteins that I have, and I couldn't find the option for printing the results as following: 

```
Target:         81 EVAKDADLVIEAIPE--IFDLKKKVFSEIEQYCP     112
                   |*||***||*|**|*  **|***|***|*****|
Query:         170 EEAKNLGLVAEVFPQERFWDEVMKLAREVAELPP     203

Length: 34
Identity:        11/34 (32.4%)
Similarity:      32/34 (94.1%)
Gaps:             2/34 ( 5.9%)
Score: 37
```

**Comment by jeffdaily** [comment]
You would like to fully duplicate the kind(s) of output from the parasail_aligner or the C API capabilities?  I suppose I just assumed Python users would be my power users and not want output like this automatically.

Would you prefer that output like this be returned to you as a string?  Or would you be okay with me simply exposing the C API that prints to C stdout?

**Comment by suzannejin** [comment]
Thanks for the answer. I've already managed to print the results as I wanted, although it could be great if it contains an option for printing or returning the stdout directly.
