### ISSUE TITLE
confuse '=' with 'X' when accessing a SAM CIGAR 

### ISSUE THREAD

**Issue by zhenLiuExplr** [jeffdaily/parasail-python#38]
Hi Jeff

I have a problem when I try to get the CIGAR from the alignment result using nw_trace().
When I try to align the two strings "TTACG" and "ACGT", with score matrix below, the CIGAR should be "1I4=" as the last four characters are equal.  But the result is "1I4X". Is there something wrong in it?

> score_matrix = parasail.matrix_create("ACGT", 1, -1)
> result = parasail.nw_trace("TTACG", "TACG", 1, 1, score_matrix)
> result.cigar.decode
b'1I4X'
> result.score
2

**Comment by jeffdaily** [comment]
github auto-closed this issue when I pushed a new tagged release v1.1.17.  There was a bug in the underlying C library introduced in release 2.4.  I fixed it a few weeks ago in the C library but failed to push out a new parasail-python tag to update the pypi package.  Please `pip install parasail -U` (to update) and try again.

**Comment by zhenLiuExplr** [comment]
Thanks! I fix it according to your suggest
