### ISSUE TITLE
Trying to install parasail without internet

### ISSUE THREAD

**Issue by cytham** [jeffdaily/parasail-python#44]
Hi,

I have been struggling to install parasail from the tar file as my server can't access the internet and hence cannot do pip install. I untar the file and do ```python setup.py install``` and got 
```
running install
parasail/libparasail.so not found, attempting to build
Downloading latest parasail master
```

And it tried to download the parasail master but couldn't due to no internet. Why is it that your package is doing this even when I already downloaded it from the master branch?

Please advise.

Thanks

cytham

**Comment by jeffdaily** [comment]
Just pushed a new release to address this issue.  Please try it out and let me know how it works for you.

Set the env var `PARASAIL_SKIP_BUILD` to avoid downloading and building the C library.  The library loading at runtime will search in the package location first (original behavior, but the library will no longer exist), followed by a direct `ctypes.CDLL(libname)` that should search system locations, followed by searching paths in environment including PARASAIL_LIBPATH, LD_LIBRARY_PATH, DYLD_LIBRARY_PATH, and PATH.

Set PARASAIL_VERBOSE=1 env var to see the progress of the library searching.
