### ISSUE TITLE
Install parasail without internet nor root permissions

### ISSUE THREAD

**Issue by GuillaumeHolley** [jeffdaily/parasail-python#47]
Hello,

I am finding myself in a very similar situation to #44 : trying to install parasail-python on a cluster with no internet. After figuring out that the install is failing because parasail-python attempts to download & install parasail-C in order to bind to it, I installed manually parasail-C on my system.

Now, my problem is that according to #26 , setup.py bdist_wheel only look for the parasail-C library at the path parasail/libparasail.so. However, I installed parasail-C in a non-default directory of my system since I am not root on my cluster. Although I understand the arguments explaining why it is like it is in #26 , I think some options should be provided for the scenario in which the install is happening on a machine with no internet and non-default install repository for parasail-C.

Thank you for your help.

Guillaume

**Comment by jeffdaily** [comment]
Just pushed a new release to address this issue.  Please try it out and let me know how it works for you.

Set the env var `PARASAIL_SKIP_BUILD` to avoid downloading and building the C library.  The library loading at runtime will search in the package location first (original behavior, but the library will no longer exist), followed by a direct `ctypes.CDLL(libname)` that should search system locations, followed by searching paths in environment including PARASAIL_LIBPATH, LD_LIBRARY_PATH, DYLD_LIBRARY_PATH, and PATH.

Set PARASAIL_VERBOSE=1 env var to see the progress of the library searching.
