### ISSUE TITLE
Shipping parasail headers inside the Python egg?

### ISSUE THREAD

**Issue by jvkersch** [jeffdaily/parasail-python#51]
Would it be possible to ship the Parasail headers along with the Python package? That would make it possible for other packages with C or Cython extensions to list this package as a dependency, and build against the headers. Right now, this is a manual step.

I have such a package here: https://github.com/enthought/vpsearch/

The headers could be added to the MANIFEST.in and the package data, and there could be a small Python entry point to list paths to the headers and library files:
```python
import parasail

parasail.get_includes()  # returns the base include dir
parasail.get_libs()  # returns the library with the parasail shared object file
```

I'd be happy to contribute a PR, if that's useful.

**Comment by jeffdaily** [comment]
Sorry for the extremely delayed response.  This seems like a useful feature.  Thanks for the suggestion.

**Comment by jvkersch** [comment]
Thanks for the follow-up @jeffdaily !
