### ISSUE TITLE
Semi-global alignment without penalties for gaps in the end of both sequences.

### ISSUE THREAD

**Issue by tprodanov** [jeffdaily/parasail-python#52]
I have two sequences and I know that they align up to some point, after that point they may or may not align.
To extend the alignment I want to use semi-global alignment that would not penalize for gaps in the end of both sequences, something like `sg_qe_de`.
For example, sequences `AAA` and `AGG` can be aligned in multiple different ways, but I would prefer
```
AAA--
A--GG
```
I can use `sg_qe_trace_scan_sat` here, but it will not align `AGG` and `AAA` correctly.

If it is not to complicated, can you implement `sg_qe_de` and `sg_qb_db` functions?

Thank you in advance.

**Comment by jeffdaily** [comment]
Added to version 1.3.

**Comment by jeffdaily** [comment]
Similar issue reported in C parasail.  https://github.com/jeffdaily/parasail/issues/95
