### ISSUE TITLE
Missing wheels on PyPI

### ISSUE THREAD

**Issue by cjw85** [jeffdaily/parasail-python#60]
Hi Jeff,

It seems you made some changes to the CI builds recently, since then the manylinux wheels haven't been being pushed to PyPI.

**Comment by jeffdaily** [comment]
Oh no!  I have no idea what's going wrong.  I'll need to check the CI logs.

**Comment by jeffdaily** [comment]
Sure enough, v1.2.3 tag failed to upload.  I'll try and revamp the travis script using the latest cibuildwheel.

**Comment by jeffdaily** [comment]
I tried updating to latest cibuildwheel package, and this has caused a bunch of new failures.  I'm still trying to figure this out.

**Comment by jeffdaily** [comment]
Fixed in release v1.2.4.  Thank you again for the report.  

If you have a moment, I'm always curious to hear how parasail is used out in the wild.  Thanks.
