### ISSUE TITLE
1.3 macos wheels

### ISSUE THREAD

**Issue by JacobHayes** [jeffdaily/parasail-python#65]
Hi, I was wondering if wheels for macos could be added back after https://github.com/jeffdaily/parasail-python/commit/b61d31bb75f5fac64e826715af156a881fdd8a58? I'd be happy to take a look and try to figure out why the build was broken if it was simply an issue of limited time in getting the release out (I totally understand that 😄).

I think at the least, we could add `stderr=subprocess.STDOUT` to the following `setup.py` subprocess call to help debug (which seems to be [the one that broke](https://github.com/jeffdaily/parasail-python/runs/7960578263?check_suite_focus=true)):

https://github.com/jeffdaily/parasail-python/blob/016c7968552f09e31f6697f0afa929e0781802f4/setup.py#L177-L180

**Comment by jeffdaily** [comment]
Please!  I don't have a macos system and I don't have the time to iterate on this using CI resources to figure out why the build failed.
