### ISSUE TITLE
Add DNA matrix

### ISSUE THREAD

**Issue by dburkhardt** [jeffdaily/parasail-python#9]
This looks like a really cool package! I'm just getting started with it, but I hope it will be useful for my research.

It would be nice if the dnafull matrix from the main implementation were available for the Python binding. It looks like the BLOSUM62 matrix could also be used, but as a new user, it's confusing to search for BLOSUM matrices and see that they are for protein alignment when I want to align DNA sequences.

I'm thinking of this: https://github.com/jeffdaily/parasail/blob/master/parasail/matrices/dnafull.h

**Comment by jeffdaily** [comment]
dnafull was added in 9fc4233be93b605ab0a32477a4742621e0d74ac7.  Thank you for your interest in parasail!
